import SwiftUI

enum Icon: String {
    case add = "plus"
    case analytics = "chart.bar.xaxis"
    case arrowBack = "chevron.backward"
    case arrowDropDown = "chevron.down"
    case arrowUp = "chevron.up"
    case battery = "battery.75percent"
    case battery5Bar = "battery.100percent"
    case bluetooth = "dot.radiowaves.left.and.right"
    case bolt = "bolt.fill"
    case build = "wrench.and.screwdriver"
    case check = "checkmark"
    case checkCircle = "checkmark.circle.fill"
    case chevronRight = "chevron.right"
    case close = "xmark"
    case cloud = "cloud"
    case delete = "trash"
    case description = "doc.text"
    case developerBoard = "cpu"
    case download = "arrow.down.circle"
    case dragHandle = "line.3.horizontal"
    case edit = "pencil"
    case error = "exclamationmark.circle.fill"
    case explore = "safari"
    case flightLand = "airplane.arrival"
    case flightTakeoff = "airplane.departure"
    case flight = "airplane"
    case fullscreen = "arrow.up.left.and.arrow.down.right"
    case gamepad = "gamecontroller"
    case height = "arrow.up.and.down"
    case help = "questionmark.circle"
    case history = "clock.arrow.circlepath"
    case home = "house"
    case lan = "network"
    case layers = "square.3.layers.3d"
    case link = "link"
    case list = "list.bullet"
    case locationOn = "mappin.and.ellipse"
    case lock = "lock.fill"
    case map = "map"
    case menu = "line.horizontal.3"
    case moreVert = "ellipsis"
    case myLocation = "location"
    case navigation = "location.north.fill"
    case notifications = "bell"
    case pause = "pause.fill"
    case photoCamera = "camera"
    case pictureInPicture = "pip"
    case play = "play.fill"
    case redo = "arrow.uturn.forward"
    case route = "point.topleft.down.to.point.bottomright.curvepath"
    case satellite = "antenna.radiowaves.left.and.right"
    case satelliteAlt = "antenna.radiowaves.left.and.right.circle"
    case science = "flask"
    case search = "magnifyingglass"
    case send = "paperplane"
    case sensors = "sensor"
    case settings = "gearshape"
    case shield = "shield"
    case signalCellular = "cellularbars"
    case signalCellularAlt = "chart.bar.fill"
    case speed = "speedometer"
    case stopCircle = "stop.circle"
    case straighten = "ruler"
    case swapHoriz = "arrow.left.arrow.right"
    case terminal = "terminal"
    case timer = "timer"
    case toggleOn = "switch.2"
    case tune = "slider.horizontal.3"
    case undo = "arrow.uturn.backward"
    case upload = "arrow.up.circle"
    case usb = "cable.connector"
    case vibration = "waveform.path"
    case videocamOff = "video.slash"
    case videocam = "video"
    case warning = "exclamationmark.triangle.fill"
    case wifi = "wifi"

    var image: Image { Image(systemName: rawValue) }
}

extension Image {
    init(_ icon: Icon) { self.init(systemName: icon.rawValue) }
}
