max_size = 30G
compression_level = 5
compiler_check = content
depend_mode = true
sloppiness = pch_defines,time_macros,include_file_mtime,include_file_ctime,locale
file_clone = true
msvc_dep_prefix = Note: including file:
